### ISSUE TITLE
Missing start or end street

### ISSUE THREAD

**Issue by russbiggs** [sharedstreets/curb-wheel-app#29]
Some streets are split by unnamed streets in OSM, not much we can do about some cases but may be worth sorting out a way to handle it so we dont get confusing screens like this:
![Screenshot_20210208-202202](https://user-images.githubusercontent.com/8487728/107311826-502b3600-6a4c-11eb-8d0c-cb75751241a0.png)

**Comment by kpwebb** [comment]
added logic for unnamed streets on some screens, but @kpwebb needs to confirm if this is being used consistently throughout the app

**Comment by russbiggs** [comment]
I can confirm this is resolved on the streets where I was experiencing it but we have a typo in "unnamed street" as "unamed street"

**Comment by kpwebb** [comment]
moving description of street labels to a shared generator function to make styling consistent

**Comment by kpwebb** [comment]
fixed in #67
