### ISSUE TITLE
common abbreviations

### ISSUE THREAD

**Issue by russbiggs** [sharedstreets/curb-wheel-app#31]
Some of the current layout issues are related to long street names and it seems like this is largely from the suffix (Street, Boulevard, Place, Way) and the quadrant (Northeast, Southeast, Southwest etc.) Although it would be language dependent, perhaps we can build in abbreviations for these common ones to reduce the likelihood of long names and create more compact text in the layout.  Thoughts? @kpwebb 

Maple Boulevard Northeast ---> Maple Blvd. NE. (saves 10 characters)

**Comment by kpwebb** [comment]
Can we included this as part of future work on internationalization workflow? perhaps we need a street name reducer regex with language specific lookup tables?

**Comment by russbiggs** [comment]
Closing this for now, localization would really make this difficult to implement.  We can reopen if it seems feasible in the future
