### ISSUE TITLE
i18n/localization

### ISSUE THREAD

**Issue by russbiggs** [sharedstreets/curb-wheel-app#53]
add framework to handle multiple languages for the app

**Comment by kpwebb** [comment]
let's examine flutter best practices and possibility of including #31 for street name normalization

**Comment by russbiggs** [comment]
To add some more clarity on the current scope of this: I think we should keep this to LTR languages, then explore RTL later if needed. Current possible needs should revolve around the existing demand for English, Spanish and French

**Comment by russbiggs** [comment]
Our template strings were a complication I didnt plan for, back to drawing board. We can probably get this into 0.9.7
