### ISSUE TITLE
Map zoom

### ISSUE THREAD

**Issue by russbiggs** [sharedstreets/curb-wheel-app#60]
It may ease usage a bit to have the map default to a valid zoom level to start surveying instead of requiring zooming in and the "Zoom in to select street".  This message is still important in case the user zooms out but should probably act more as a warning for behavior than the default state.

**Comment by russbiggs** [comment]
@kpwebb should we close this after the work in 0.9.7? or should we keep it open given the lingering issues?

**Comment by kpwebb** [comment]
Closing with a partial fix, and opened #105 to address underlying problem in flutter Mapbox lib.
